notifications:
  email: false
language: node_js
node_js:
- node
deploy:
  provider: npm
  email:
    secure: UjxLfabMzsUa//VZqbVxeL4AIjsSk+CAMssrVWLZ53QTGgxnVFhH1Cu4PFc6pMKEvXK849mkDAyef+y4ioFI5DKWllQi2puk2tYhIP+CoGQzOlVIhq4MqnSx7NibiOPHGCanYzzkt9uof0z8J/h3smLuKAiJnPLE0UZIa5eOz70CTUTg0lz/NOvXdD9TB3eJE5bL9SB4X+2TSFGe/0W2miGC2qXtWIIQGPzCDKjGU0eBJiQxnF93ox7mxt9l1lBVoSDZbCqM2zyLqrXj4XnzZpBlcMiupXdTT8bW4lNp8nhYDUjgmUsPksWX8Hh8T7zXYsvP+mIrUQUNlUocOQyDpAKKnFQVhtDqpVm2RX5rBaMUaQfwe4xsNV0rA8Zu3rh7tvPGvrMwP3VjAVlft5n4kjo03J/V3uFsJNCr3IuALXAdgDNH6tb9oVJvxp3PH9nC3yxqLEPm+EyK8J52TPO2O+Tn9nvT5aopk3KVAVgv+XM7HjiZoLA5+SixgxernoEsgAoA/P8O+KD/QQMiCAc8sU+SFzMXGwmb414fDIjx0BODDSqledWCJ2/N024RFzMyG9LQiI+CVF9rDg5O9TIEqi1ENjVMSLFuf0Ui//0PQdN6AMlZcoe4NYvd0UpU9LyHcLx5Wb8nGjAinSNbGPAcIHON+NufyxCEKfBbRx/AjnI=
  api_key:
    secure: iOvZKA+WIj0A/OPYFlVKFN4WA/CuxeQ0wHmBRCYXvj38ayFJrVQKmH0Gvs6kFLx9gs+2DSqdsYebS5XUXN39oMWtzDZnUd3p9Y9Dwr21jqruJYcWh+WYhQqVNuZ9LxJBIx6NlapPkiQtKFzD+sFsFN0e+l7INZafYKMP6vqywwUXs8k5oq1JFkPVLaoiJshV4Yc7pzNMxMIScL9dt0tamKC+pYrnTS1gY84kDUJQn0zebNQ8i0Bg0wbDiVVhpJieZ99/+SUrb5cz52swrdHy0VlsQeZz9ldeG2VulQTBiN4vIDoIa3BAsqgYI+rULlNalUuT7H80N2CeIlOD762YKRdKCC+FHWVVPBwiflDT54/U+FYkd4fihp/tQacxuyswYAgxBUTNzfhP1QN6DQFsaFzOhp1xkXyQXxTVzMQVbD2fIvr2JaGy71CO8gMgh2uUHFmdp5C2iATi6jqKdtiC5AGdzIXTb+mzGhxuv6j3XYyxpQkoZHP75+vbPrwAg17Dw8jwUQN/pn0Xig8cXP1x7xgCLNlDuW7/CLteS0GLFyzex7IlfUJikA13f5G6YrP5ycUAepE9/TolEfl6aGOSyuavB3MePA2Oe8lpI8zTZOPrdbTy9VNW5D0e7ItV/SzBTLYaqq1NRNlUNcTR5zxwNYlExhh3dKcBooIGM/BesLE=
  on:
    tags: true
